version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: agentguide-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agentguide
    ports:
      - "5432:5432"
    volumes:
      # Persist database data between restarts
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agentguide-backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/agentguide?schema=public"
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    # Auto-restart on failure
    restart: unless-stopped

volumes:
  # Named volume for persistent PostgreSQL data
  postgres_data:
